# -*- coding: utf-8 -*-
"""client.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_VJoLvImhnNm1bQ9I8orln9vVoMzBoI
"""

import asyncio
import websockets

async def send_message():
    uri = "ws://localhost:8889"
    async with websockets.connect(uri) as websocket:
        while True:
            message = "Hello! This is my submission for the course - AI4014!"
            await websocket.send(message)
            print(f"Sent to server: {message}")

            response = await websocket.recv()
            print(f"Received from server: {response}")

# Running the client's sending loop
asyncio.get_event_loop().run_until_complete(send_message())