# -*- coding: utf-8 -*-
"""server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_VJoLvImhnNm1bQ9I8orln9vVoMzBoI
"""

import asyncio
import websockets

# Define the server's behavior when a connection is established
async def server_handler(websocket, path):
    async for message in websocket:
        print(f"Received from client: {message}")
        await websocket.send(response)
        print(f"Sent to client: Okay!")

# Start the server
start_server = websockets.serve(server_handler, "localhost", 8765)

# Run the server until it's manually stopped
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()